### ISSUE TITLE
can not load my controller

### ISSUE THREAD

**Issue by avivaWang** [ocombe/ocLazyLoad#157]
Hi:
Here is my code:
```javascript
define(['app'], function (app) {
    app.config(['$stateProvider', '$urlRouterProvider', function ($stateProvider, $urlRouterProvider ) {
        $urlRouterProvider.otherwise("/index");
        $stateProvider
            .state('index', {
                url: '/index',
                templateUrl: 'template/index/index.html'
            })
            .state('list', {
                url: '/list',
                views: {
                    "lazyLoadView": {
                        controller: "listCtrl as app", // This view will use AppCtrl loaded below in the resolve
                        templateUrl: "template/list/list1.html"
                    }
                },
                resolve: {
                    list: ['$ocLazyLoad', function ($ocLazyLoad) {
                        return $ocLazyLoad.load({
                            name: 'MyApp',
                            files: ['js/controller/listControl.js']
                        });
                    }]
                }
            })
            .state('list2', {
                url: '/list2',
                views: {
                    "lazyLoadView": {
                        controller: "listCtrl as MyApp", // This view will use AppCtrl loaded below in the resolve
                        templateUrl: "template/list/list2.html"
                    }
                },
                resolve: {
                    list: ['$ocLazyLoad', function ($ocLazyLoad) {
                        return $ocLazyLoad.load({
                            name: 'MyApp',
                            files: ['js/controller/listControl.js']
                        });
                    }]
                }
            })
            .state('document', {
                url: '/document',
                templateUrl: 'template/list/list2.html',
                controller: function ($scope, $stateParams) {
                    $scope.listId = $stateParams.listId;
                }
            })
    }]);
});
```
and the controller is like that:
```javascript
define(['app'], function (app) {
    app.controller('listCtrl', function ($scope, $ocLazyLoad) {
        $scope.$on('ocLazyLoad.moduleLoaded', function(e, params) {
            //console.log('event module loaded', params);
        });
        $scope.person = {
            name: "4444"
        };
    });
    app.$inject = ['$scope'];
});
```

but, when I run this code, I got an error ：Error: [ng:areq] Argument 'listCtrl' is not a function, got undefined

how can I fix this problem?

**Comment by image72** [comment]
ocLazyLoad can't execute loading AMD module...
same as you

**Comment by avivaWang** [comment]
Hi， I have worked out  this issue， I use an older ocLazyLoad.js replace the newest one, then this problem was solved。

**Comment by image72** [comment]
@avivaWang please tell me, which version used ?

I used bower release version **0.6.3**

**Comment by avivaWang** [comment]
@image72 , the version I used is 0.5.1.

**Comment by image72** [comment]
@avivaWang thanks a lot. :+1:

**Comment by ocombe** [comment]
Hi, sorry for the lack of answer, I was in London for a few days.
Yes, executing amd modules is not working because they will be executed asynchronously and the code won't be available when the lib tries to register the components.
If you need to load amd modules, you'll need to use a compatible loader such as requirejs.
With the v1.0 it will be easier to write new loader for cases like this, so writing an amd loader should be possible.

On the other end, I don't know why it was working in 0.5.1 :)
