### PR TITLE
Fix #221

### LINKED ISSUE #221: Angular 1.4.x with ocLazyLoad 1.0.4 fails to load controller.
Seems like there may be a regression from 1.0.3 to 1.0.4.  The following code works in 1.0.3 and fails in 1.0.4.  The error generated is...

Error: [ng:areq] Argument 'sftSearchController' is not a function, got undefined
http://errors.angularjs.org/1.4.2/ng/areq?p0=sftSearchController&p1=not%20aNaNunction%2C%20got%20undefined
    at REGEX_STRING_REGEXP (http://cdn.jsdelivr.net/angularjs/1.4.2/angular.js:68:12)
    at assertArg (http://cdn.jsdelivr.net/angularjs/1.4.2/angular.js:1770:11)
    at assertArgFn (http://cdn.jsdelivr.net/angularjs/1.4.2/angular.js:1780:3)
    at http://cdn.jsdelivr.net/angularjs/1.4.2/angular.js:8977:9
    at compile (webpack:///./~/angular-ui-router/release/angular-ui-router.js?:4018:28)
    at invokeLinkFn (http://cdn.jsdelivr.net/angularjs/1.4.2/angular.js:8652:9)
    at nodeLinkFn (http://cdn.jsdelivr.net/angularjs/1.4.2/angular.js:8152:11)
    at compositeLinkFn (http://cdn.jsdelivr.net/angularjs/1.4.2/angular.js:7543:13)
    at publicLinkFn (http://cdn.jsdelivr.net/angularjs/1.4.2/angular.js:7418:30)
    at updateView (webpack:///./~/angular-ui-router/release/angular-ui-router.js?:3959:23)

    .config({
      'sft': {
        abstract: true,
        controller: 'sftAppController',
        templateUrl: 'src/app/views/app.html'
      },
      'sft.search': {
        url: '/search',
        templateUrl: 'src/app/views/page.html',
        controller : 'sftSearchController',
        data: {
          index: APP_DATA.site.hasElasticSearch,
          follow: APP_DATA.site.hasElasticSearch
        },
        resolve: {
          searchBundle: ['$q', '$ocLazyLoad', function($q, $ocLazyLoad) {
              var deferred = $q.defer();
              require.ensure(['../searchApp.js'], function(require) {
                var mod = require('../searchApp.js');
                $ocLazyLoad.load({
                      name: 'ari.endvr.sft.app.search'
                  });
                  deferred.resolve(mod.controller);
              }, 'searchBundle');
              return deferred.promise;
        }]
      }
    },
    'sft.search.list': {
      url: '/:type',
      template: '<div ui-view></div>'     
    },
    'sft.search.list.recommended': {
      url: '/recommended/{params:RawValue}',
      recommended: true,
      controller: 'sftSearchListController',
      templateUrl: 'src/widgets/search/views/lists/recommended.html'
    },
    'sft.search.list.studio': {
      url: '/studio/{params:RawValue}',
      studio: true,
      controller: 'sftSearchListController',
      templateUrl: 'src/widgets/search/views/lists/default.html'
    },
    'sft.search.list.default': {
      url: '/{params:RawValue}',
      controller: 'sftSearchListController',
      templateUrl: 'src/widgets/search/views/lists/default.html'
    },

### PR DESCRIPTION
**Pull request by phenomnomnominal**
_addToLoadList needs to be called with ‘real’ when called from inject
if the actual module has been created by a different loader.

### CODE REVIEW

**Comment by ocombe** [comment]
Nice! I'm checking this tonight, thanks for your help :)
